#!/usr/bin/env node

import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = join(__dirname, '..');

// Paths to template files
const templateDir = join(projectRoot, 'src', 'view-hierarchy', 'xsl');
const xslTemplatePath = join(templateDir, 'template.xsl');
const cssTemplatePath = join(templateDir, 'template.css');
const jsTemplatePath = join(templateDir, 'template.js');
// Fixture paths for both platforms
const iosXmlPath = join(templateDir, '__fixtures__', 'ios.xml');
const iosPngPath = join(templateDir, '__fixtures__', 'ios.png');
const androidXmlPath = join(templateDir, '__fixtures__', 'android.xml');
const androidPngPath = join(templateDir, '__fixtures__', 'android.png');
const errorXmlPath = join(templateDir, '__fixtures__', 'error.xml');

// Output paths
const outputPath = join(templateDir, 'index.ts');
const iosNoBgPath = join(templateDir, '__fixtures__', 'ios-no-bg.temp.xml');
const iosBgPath = join(templateDir, '__fixtures__', 'ios-bg.temp.xml');
const androidNoBgPath = join(templateDir, '__fixtures__', 'android-no-bg.temp.xml');
const androidBgPath = join(templateDir, '__fixtures__', 'android-bg.temp.xml');
const errorTempPath = join(templateDir, '__fixtures__', 'error.temp.xml');

console.log('🔄 Generating XSL template...');

try {
  // Read template files
  const xslTemplate = readFileSync(xslTemplatePath, 'utf-8');
  const cssContent = readFileSync(cssTemplatePath, 'utf-8');
  const jsContent = readFileSync(jsTemplatePath, 'utf-8');

  // Escape content for XML/HTML embedding
  function escapeXmlContent(content) {
    return content
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;');
  }

  // Replace placeholders in XSL template with properly escaped content
  let combinedTemplate = xslTemplate
    .replace('<!-- CSS_PLACEHOLDER -->', escapeXmlContent(cssContent))
    .replace('<!-- JS_PLACEHOLDER -->', escapeXmlContent(jsContent));

  // Generate TypeScript file with plain XML string
  const tsContent = `// This file is auto-generated by scripts/generate-xsl.mjs
// Do not edit manually - edit template files instead

export default ${JSON.stringify(combinedTemplate)};
`;

  // Write the generated file
  writeFileSync(outputPath, tsContent, 'utf-8');

  // Write standalone XSL file to root directory for npm package
  const standaloneXslPath = join(projectRoot, 'view-hierarchy.xsl');
  writeFileSync(standaloneXslPath, combinedTemplate, 'utf-8');

  // Generate derivative XML files
  console.log('🔄 Generating derivative XML files...');

  // Convert to data URL for derivative files
  const dataUrl = `data:application/xml;charset=utf-8,${encodeURIComponent(combinedTemplate)}`;

  // Create XSL processing instruction
  const xslPi = `<?xml-stylesheet type="application/xml" href="${dataUrl}"?>\n`;

  // Helper function to generate derivative files for a platform
  function generatePlatformFiles(platform, xmlPath, pngPath, noBgPath, bgPath) {
    console.log(`🔄 Processing ${platform} files...`);

    // Read the original fixture XML
    const fixtureXml = readFileSync(xmlPath, 'utf-8');

    // Generate no-bg.temp.xml (without background)
    const fixtureNoBg = fixtureXml.replace(
      '\n',
      `\n${xslPi}\n`
    );
    writeFileSync(noBgPath, fixtureNoBg, 'utf-8');

    // Generate bg.temp.xml (with background)
    const fixtureWithBg = fixtureXml.replace(
      '\n',
      `\n${xslPi}\n`
    ).replace(
      /\<ViewHierarchy\b/m,
      `<ViewHierarchy screenshot="data:image/png;base64,${readFileSync(pngPath, 'base64')}"`
    );
    writeFileSync(bgPath, fixtureWithBg, 'utf-8');
  }

  // Generate files for both platforms
  generatePlatformFiles('iOS', iosXmlPath, iosPngPath, iosNoBgPath, iosBgPath);
  generatePlatformFiles('Android', androidXmlPath, androidPngPath, androidNoBgPath, androidBgPath);

  // Generate error temp file (no background version needed)
  console.log('🔄 Processing test error fixture...');
  const errorXml = readFileSync(errorXmlPath, 'utf-8');
  const errorTemp = errorXml.replace(
    '\n',
    `\n${xslPi}\n`
  );
  writeFileSync(errorTempPath, errorTemp, 'utf-8');

  console.log('✅ Generated XSL template successfully');
  console.log(`📁 Output: ${outputPath}`);
  console.log(`📁 Standalone XSL: ${standaloneXslPath}`);
  console.log(`📁 iOS No-bg fixture: ${iosNoBgPath}`);
  console.log(`📁 iOS Bg fixture: ${iosBgPath}`);
  console.log(`📁 Android No-bg fixture: ${androidNoBgPath}`);
  console.log(`📁 Android Bg fixture: ${androidBgPath}`);
  console.log(`📁 Error test fixture: ${errorTempPath}`);
  console.log(`📊 Size: ${Math.round(combinedTemplate.length / 1024)}KB`);

} catch (error) {
  console.error('❌ Error generating XSL template:', error.message);
  process.exit(1);
}
